config/routes.rb
Rails.application.routes.draw do

  get 'errors/file_not_found'

  get 'errors/unprocessable'

  get 'errors/internal_server_error'

  get 'errors/access_denied'

  get 'home/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admins, :controllers => { :admins => "admins" }
  devise_for :secretaries, :controllers => { :secretaries => "secretaries" }

  root 'home#index'
  get '/sistema' => 'home#sys'
  get '/prof' => 'home#index'
  get '/about' => 'home#about', as: :about
  get '/professors/sign_in/' => 'home#index'
  get "/users/sign_in/" => "home#index"

  resources :users, except: :edit

  resources :admins do
    collection do
      get :control_panel
      post :duplicate_students
      post :register_undergraduate_courses
      post :register_postgraduate_courses
    end
  end

  resources :advises
  post 'advises/:id/moveup' => 'advises#moveup', as: :moveup_advise
  post 'advises/:id/movedown' => 'advises#movedown', as: :movedown_advise

  resources :request_for_teaching_assistants, except: [:new]
  get 'request_for_teaching_assistants/:semester_id/new' => 'request_for_teaching_assistants#new', as: :new_request_for_teaching_assistant
  get 'request_for_teaching_assistants_for_semester/:semester_id/' => 'request_for_teaching_assistants#index_for_semester', as: :request_for_teaching_assistants_for_semester
  get 'request_for_teaching_assistants_for_professor/:professor_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor
  get 'request_for_teaching_assistants_for_professor_and_semester/:professor_id/:semester_id/' => 'request_for_teaching_assistants#index_for_professor', as: :request_for_teaching_assistants_for_professor_and_semester

  resources :professors
  get 'professors/:id/change_password' => 'professors#change_password', as: :change_professor_password
  post 'professors/:id/make_superprofessor' => 'professors#make_superprofessor', as: :make_super_professor

  resources :courses

  resources :secretaries
  get 'secretaries/:id/change_password' => 'secretaries#change_password', as: :change_secretary_password

  resources :students, except: :show

  resources :assistant_frequency do
    collection do
      get :index
      post :request_frequency
    end
  end

  get 'dumps/' => 'dumps#index', as: :dumps

  get 'assistant_frequency/monthly_control/:semester_id/:month/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control
  get 'assistant_frequency/monthly_control/:semester_id/:month/:department_id/:filter' => 'assistant_frequency#monthly_control', as: :assistant_frequency_monthly_control_for_department
  get 'assistant_frequency/:id/edit_comment' => 'assistant_frequency#edit_comment', as: :edit_assistant_frequency_comment
  post 'assistant_frequency/open_period/:semester_id/:month/:last_filter' => 'assistant_frequency#open_frequency_period', as: :open_frequency_period
  post 'assistant_frequency/close_period/:semester_id/:month/:last_filter' => 'assistant_frequency#close_frequency_period', as: :close_frequency_period
  post 'assistant_frequency/request_frequency/' => 'assistant_frequency#request_frequency', as: :request_frequency
  post 'assistant_frequency/mark_generic_assistant_role_frequency/' => 'assistant_frequency#mark_generic_assistant_role_frequency', as: :mark_generic_assistant_role_frequency
  post 'assistant_frequency/mark_assistant_role_frequency/' => 'assistant_frequency#mark_assistant_role_frequency', as: :mark_assistant_role_frequency
  post 'assistant_frequency/:id/comment' => 'assistant_frequency#update_comment', as: :update_assistant_frequency_comment
  post 'assistant_frequency/pay_all_assistants/:semester_id/:month' => 'assistant_frequency#pay_all_assistants', as: :pay_all_assistants

  resources :semesters
  post 'semesters/:id/open' => 'semesters#open', as: :open_semester
  post 'semesters/:id/activate' => 'semesters#activate', as: :activate_semester
  post 'semesters/:id/close' => 'semesters#close', as: :close_semester
  post 'semesters/:id/deactivate' => 'semesters#deactivate', as: :deactivate_semester
  post 'semesters/:id/open_evaluation_period' => 'semesters#open_evaluation_period', as: :open_semester_evaluation_period
  post 'semesters/:id/close_evaluation_period' => 'semesters#close_evaluation_period', as: :close_semester_evaluation_period

  resources :candidatures, except: :new
  get 'candidatures/:id/download_transcript' => 'candidatures#download_transcript', as: :download_candidature_transcript
  get 'candidatures/:semester_id/new' => 'candidatures#new', as: :new_candidature
  get 'candidatures/list/:department_id/' => 'candidatures#index', as: :candidatures_with_department
  get 'candidatures/for_department/:semester_id/:department_id/' => 'candidatures#index_for_department', as: :candidatures_for_department
  get 'candidatures/for_student/:student_id/' => 'candidatures#index_for_student', as: :candidatures_for_student

  get 'assistant_roles/' => 'assistant_roles#index', as: :assistant_roles
  get 'assistant_roles/for_semester/:semester_id' => 'assistant_roles#index', as: :assistant_roles_for_semester
  get 'assistant_roles/for_semester/:semester_id/:department_id' => 'assistant_roles#index', as: :assistant_roles_for_semester_and_department
  get 'assistant_roles/for_professor/:professor_id/' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor
  get 'assistant_roles/for_professor/:professor_id/:semester_id' => 'assistant_roles#index_for_professor', as: :assistant_roles_for_professor_and_semester
  get 'assistant_roles/certificate/:id' => 'assistant_roles#certificate', as: :certificate
  get 'assistant_roles/report_form/:id' => 'assistant_roles#report_form', as: :report_form
  get 'assistant_roles/print_report/:id' => 'assistant_roles#print_report', as: :print_report
  get 'assistant_roles/:request_for_teaching_assistant_id/new' => 'assistant_roles#new', as: :new_assistant_role
  post 'assistant_roles/notify_for_semester/:semester_id' => 'assistant_roles#notify_for_semester', as: :notify_assistant_roles_for_semester
  post 'assistant_roles/request_evaluations_for_semester/:semester_id' => 'assistant_roles#request_evaluations_for_semester', as: :request_assistant_evaluations_for_semester
  post 'assistant_roles/:request_for_teaching_assistant_id/:student_id/create' => 'assistant_roles#create', as: :create_assistant_role
  post 'assistant_roles/deactivate_assistant_role/:id' => 'assistant_roles#deactivate_assistant_role', as: :deactivate_assistant_role
  post 'assistant_roles/reactivate_assistant_role/:id' => 'assistant_roles#reactivate_assistant_role', as: :reactivate_assistant_role
  patch 'assistant_roles/:id/' => 'assistant_roles#update', as: :update_assistant_role
  delete 'assistant_roles/:id/' => 'assistant_roles#destroy', as: :destroy_assistant_role

  resources :assistant_evaluations, except: [:index, :show, :new, :destroy]
  get 'assistant_evaluations/for_student/:student_id/' => 'assistant_evaluations#index_for_student', as: :assistant_evaluations_for_student
  get 'assistant_evaluations/:assistant_role_id/new' => 'assistant_evaluations#new', as: :new_assistant_evaluation

  get "help_students/:id" => "help_students#index", :as => :help_students

  get "help_professors/:id" => "help_professors#index", :as => :help_professors

  match '/403', to: 'errors#access_denied', via: :all
  match '/404', to: 'errors#file_not_found', via: :all
  match '/422', to: 'errors#unprocessable', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  devise_scope :user do
    match '/users/auth/USP/callback', to: 'users/omniauth_callbacks#usp', via: [:get, :post]
  end

  get '/_instructions' => redirect('http://www.ime.usp.br/grad/monitoria'), as: :official_instructions

end

app/controllers/assistant_roles_controller.rb
class AssistantRolesController < ApplicationController
  authorize_resource

  # GET /assistant_roles
  def index
    get_semester
    get_department
    if should_see_all_roles?
      if params[:department_id].present?
        @assistant_roles = AssistantRole.for_department_and_semester @department, @semester
      else
        @assistant_roles = AssistantRole.for_semester @semester
      end
        p @assistant_roles
    else
      @assistant_roles = AssistantRole.for_semester @semester
      @assistant_roles = @assistant_roles.map { |x| x }.keep_if do |role|
        should_see_the_role role
      end
    end
  end

  # GET /assistant_roles/for_professor/1
  def index_for_professor
    get_semester
    @professor = Professor.find(params[:professor_id])
    raise CanCan::AccessDenied.new unless current_user.professor == @professor
    @assistant_roles = AssistantRole.for_professor_and_semester @professor, @semester
  end

  # GET /assistant_roles/new
  def new
    @request = RequestForTeachingAssistant.find(assistant_role_params[:request_for_teaching_assistant_id])
    if @request.incomplete?
      @first_option_candidatures = sort_candidates(Candidature.all_first_options_for_request @request)
      @nonfirst_option_candidatures = sort_candidates(Candidature.all_nonfirst_options_for_request @request)
      @same_department_candidatures = sort_candidates(Candidature.all_for_same_department_request @request)
      if search_params[:nusp].present?
        @other_candidatures = sort_candidates(Candidature.for_nusp_and_semester search_params[:nusp], @request.semester)
      else
        @other_candidatures = []
      end
    else
      redirect_to @request
    end
  rescue ActiveRecord::RecordNotFound
    raise ActionController::RoutingError.new('Not Found')
  end

  def create
    @assistant_role = AssistantRole.new assistant_role_params
    student_exists = Student.exists? @assistant_role.student_id
    request_exists = RequestForTeachingAssistant.exists? @assistant_role.request_for_teaching_assistant_id
    if student_exists and request_exists
      @assistant_role.started_at = [Time.now, @assistant_role.standard_first_day].max
      if @assistant_role.save
        respond_to do |format|
          BackupMailer.new_assistant_role(@assistant_role, current_creator).deliver
          format.html { redirect_to @assistant_role.request_for_teaching_assistant, notice: 'Monitor eleito com sucesso.' }
          format.json { render action: 'show', status: :created, location: @assistant_role.request_for_teaching_assistant }
        end
      end
    elsif request_exists
      respond_to do |format|
        format.html { redirect_to @assistant_role.request_for_teaching_assistant, notice: 'Erro ao criar monitor.' }
        format.json { render json: @assistant_role.errors, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        format.html { redirect_to '/', notice: 'Erro ao criar monitor.' }
        format.json { render json: @assistant_role.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if AssistantRole.exists? params[:id]
      @assistant_role = AssistantRole.find params[:id]
      BackupMailer.delete_assistant_role(@assistant_role, current_creator).deliver
      @assistant_role.destroy
      respond_to do |format|
        format.html { redirect_to assistant_roles_path }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to assistant_roles_path }
        format.json { head :no_content }
      end
    end
  end

  def update
    @assistant_role = AssistantRole.find params[:id]
    @assistant_role.student_amount = params[:assistant_role][:student_amount]
    @assistant_role.homework_amount = params[:assistant_role][:homework_amount]
    @assistant_role.secondary_activity = params[:assistant_role][:secondary_activity]
    @assistant_role.workload = params[:assistant_role][:workload]
    @assistant_role.workload_reason = params[:assistant_role][:workload_reason]
    @assistant_role.comment = params[:assistant_role][:comment]
    @assistant_role.report_creation_date = params[:assistant_role][:report_creation_date]
    @assistant_role.save
    redirect_to candidatures_path
  end

  # POST /assistant_roles/notify_for_semester/1
  def notify_for_semester
    @semester = Semester.find(params[:semester_id])
    requests = RequestForTeachingAssistant.where(semester: @semester)
    AssistantRole.where(request_for_teaching_assistant: requests).each do |assistant|
      NotificationMailer.acceptance_notification(assistant).deliver
    end
    respond_to do |format|
      format.html { redirect_to assistant_roles_path, notice: "Monitores do #{@semester.as_s} notificados com sucesso." }
      format.json { render action: 'index' }
    end
  end


  # POST /assistant_roles/request_for_teaching_assistant_id/1
  def request_evaluations_for_semester
    @semester = Semester.find(params[:semester_id])
    AssistantEvaluation.request_evaluations_for_semester @semester
    respond_to do |format|
      format.html { redirect_to assistant_roles_path, notice: "Solicitações enviadas aos professores do #{@semester.as_s} com sucesso." }
      format.json { render action: 'index' }
    end
  end

  def deactivate_assistant_role
    if AssistantRole.exists? params[:id]
      @assistant_role = AssistantRole.find params[:id]
      @assistant_role.deactivate
      respond_to do |format|
        format.html { redirect_to assistant_roles_path }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to assistant_roles_path }
        format.json { head :no_content }
      end
    end
  end

  def reactivate_assistant_role
    if AssistantRole.exists? params[:id]
      @assistant_role = AssistantRole.find params[:id]
      @assistant_role.reactivate
      respond_to do |format|
        format.html { redirect_to assistant_roles_path }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to assistant_roles_path }
        format.json { head :no_content }
      end
    end
  end

  def certificate
    if AssistantRole.exists? params[:id]
      @assistant = AssistantRole.find params[:id]
      if @assistant.student.is_female?
        @genderfied_title = "aluna-monitora"
      else
        @genderfied_title = "aluno-monitor"
      end
      render pdf: "Certificado #{@assistant.student.name}"
    else
      respond_to do |format|
        format.html { redirect_to assistant_roles_path, notice: "Erro ao gerar atestado."}
        format.json { render action: 'index'}
      end
    end
  end

  def report_form
    @role = AssistantRole.find params[:id]
    check_evaluation_period @role
  end

  def print_report
    if AssistantRole.exists? params[:id]
      @assistant = AssistantRole.find params[:id]
      render pdf: "Relatório #{@assistant.student.name}"
    end
  end

  private

  def sort_candidates candidates
    candidates.map{ |x| x }.sort! { |a, b| a.student.name <=> b.student.name }
  end

  def check_evaluation_period role
    raise CanCan::AccessDenied.new unless role.semester.evaluation_period
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def assistant_role_params
    params.permit(
      :student_id, :request_for_teaching_assistant_id
    )
  end

  def search_params
    params.permit(:nusp)
  end

  def get_semester
    if params[:semester_id].present?
      @semester = Semester.find params[:semester_id]
    else
      @semester = Semester.last_active_but_closed
      if @semester.nil?
        @semester = Semester.last
      end
    end
  end

  def get_department
    if params[:department_id].present?
      @department = Department.find params[:department_id]
    else
      @department = nil
    end
  end

  def should_see_all_roles?
    current_hiper_professor? or secretary_signed_in?
  end

  def should_see_the_role role
    (current_super_professor? and role.course.dep_code == current_user.professor.dep_code) \
    or \
    (current_professor? and role.request_for_teaching_assistant.professor == current_user.professor)
  end

  def separate_by_semester record
    @assistant_roles_by_semester = Semester.all.reverse_order.map do |semester|
      {
        semester: semester,
        role: record.map { |x| x }.keep_if do |role|
          ((role.request_for_teaching_assistant.semester == semester) and
            (should_see_all_roles? or should_see_the_role(role)))
        end
      }
    end
    @assistant_roles_by_semester.each do |entry|
      entry[:role].sort! { |a, b| a.student.name <=> b.student.name }
    end
  end


  def create_current_months roles
    @months = [Time.now.month]
    if @current_semester_frequencies
      @current_semester_frequencies.each do |freq|
        @months.push(freq.month)
      end
    else
      roles.each do |role|
        role.assistant_frequency.each do |freq|
          @months.push(freq.month)
        end
      end
    end
    @months.uniq!
    @months.sort!
  end

  def current_creator
    if secretary_signed_in?
      current_secretary
    elsif user_signed_in?
      current_user.professor
    end
  end
end

app/helpers/assistant_roles_helper.rb
module AssistantRolesHelper
  def months_to_names
    [
      '',
      'Janeiro',
      'Fevereiro',
      'Março',
      'Abril',
      'Maio',
      'Junho',
      'Julho',
      'Agosto',
      'Setembro',
      'Outubro',
      'Novembro',
      'Dezembro'
    ]
  end
  def workloads
    [
      ["Pesado", 0],
      ["Razoável", 1],
      ["Leve", 2]
    ]
  end
end

app/views/assistant_roles/_candidates.html.erb
<% if !title.nil? and !title.empty? %>
<h4><%= title %></h4>
<% end %>

<% if candidates.any? %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Nº USP</th>
        <th>Já foi eleito?</th>
        <th colspan=\"2\"></th>
      </tr>
    </thead>
    <tbody>
      <% candidates.each do |candidature| %>
        <% if candidature.elected? %>
          <tr class="elected">
        <% else %>
          <tr>
        <% end %>
        <td><%= candidature.student.name %></td>
        <td><%= candidature.student.nusp.to_s %></td>
        <td><%= show_yes_or_no(candidature.elected?) %></td>
        <td><%= link_to('Detalhes', candidature, class: "btn btn-primary") %></td>
        <% if candidature.elected? %>
          <td><%= button_link_to('Eleger', create_assistant_role_path(@request, candidature.student, class: "btn btn-primary"),
          method: :post, data: {confirm: "Este estudante já foi eleito para monitor(a) de outra disciplina, está certo que deseja elegê-lo(a) novamente?"}) %></td>
        <% else %>
          <td><%= button_link_to('Eleger', create_assistant_role_path(@request, candidature.student), method: :post, class: "btn btn-primary") %></td>
        <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p><i>Nenhum candidato nesta categoria</i></p>
<% end %>

app/views/assistant_roles/index.html.erb
<h1>Monitores eleitos para <%= @semester.as_s %></h1>

<div class="row" style="height:1em;"></div>

<div class="row">
  <div class="col-sm-3">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        <%= @semester.as_s %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% Semester.all.order(created_at: :desc).each do |semester| %>
          <li><%= link_to semester.as_s, assistant_roles_for_semester_path(semester)%></li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <% if (secretary_signed_in? or current_hiper_professor?) %>
    <div class="col-sm-1">
      <div class="dropdown">
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
          <% if @department.nil? %>
            Todos
          <% else %>
            <%= @department.code %>
          <% end %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to "Todos", assistant_roles_for_semester_path(@semester) %>
          </li>
          <% Department.all.order(code: :desc).each do |department| %>
            <li><%= link_to department.code, assistant_roles_for_semester_and_department_path(@semester, department)%></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  
  <% if secretary_signed_in? and @semester.current? %>
    <div class="col-sm-2">
      <%= button_link_to "Notificar monitores", notify_assistant_roles_for_semester_path(@semester), method: :post %>
    </div>
    <div class="col-sm-2">
      <% unless Rails.env.production? %>
        <%= button_link_to "Pedir avaliações dos professores", request_assistant_evaluations_for_semester_path(@semester), method: :post %>
      <% end %>
    </div>
  <% else %>
    <div class="col-sm-10"></div>
  <% end %>
</div>

<div class="row" style="height:1em;"></div>

<table id="roles_table" class="table table-hover">
  <thead>
    <tr>
      <th>Aluno(a)</th>
      <th>Disciplina</th>
      <th>Professor(a)</th>
      <th>Início</th>
      <th>Fim</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @assistant_roles.each do |role| %>
      <tr>
        <td>
    			<% if role.student.name != nil %>
            <%=  role.student.name %>
    			<% else %> Nil <% end %>
		    </td>
        <td><%= role.course.course_code %></td>
        <td><%= role.professor.name %></td>

        <!--  Data de incio -->
        <td>
    			<% if not role.started_at.nil? %>
    				<%= role.started_at.strftime("%d/%m/%Y") %>
    			<% else %>
  				  Nil
  			   <% end %>
  		  </td>

        <!--  Data de fim -->
        <td>
          <% if role.started_at? %>
            <%= role.started_at.strftime("%d/%m/%Y") %>
          <% else %>
            Nil
          <% end %>
        </td>
        
        <% if secretary_signed_in? or current_super_professor? %>
          <td>
            <%if role.active %>
              <% if secretary_signed_in? %>
                <%= small_button_link_to "Desativar", deactivate_assistant_role_path(role.id), method: :post, data: { confirm: 'Deseja mesmo desativar este monitor?' } %>
              <% else %>
                Ativo
              <% end %>
            
            <% else %>
              Desativado
              <%= small_button_link_to "Reativar", reactivate_assistant_role_path(role.id), method: :post, data: { confirm: 'Deseja mesmo reativar este monitor?' } %>
            <% end %>
          </td>
          
        <% end %>

        <td>
          <% if role.report_filled? %>
          <%= small_button_link_to 'Ver relatório', print_report_path(role.id, :format => :pdf), target: "_blank" %>
          <% end %>
        </td>

        <% if secretary_signed_in? or admin_signed_in? %>
          <td>
            <%= small_button_link_to "Atestado", certificate_path(role.id, :format => :pdf), method: :get, target: "_blank" %>
          </td>
          <td>
            <%= small_button_link_to "Remover", destroy_assistant_role_path(role), method: :delete, data: { confirm: 'Deseja mesmo remover PERMANENTEMENTE esse monitor?'} %>
          </td>
        <% else %>
            <td></td>
            <td></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/assistant_roles/index_for_professor.html.erb
<h1>Meus monitores</h1>

<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end -%>

<div class="row">
  <div class="col-sm-4">
    <div class="dropdown">
      <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
        <%= @semester.as_s %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <% Semester.all.reverse.each do |semester| %>
          <li><%= link_to semester.as_s, assistant_roles_for_professor_and_semester_path(@professor, semester)%></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-sm-8"></div>
</div>

<div class="row" style="height:1em;"></div>

<ul class="list-group">
  <% @assistant_roles.each do |role| %>
    <li class="list-group-item">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-4">
            <h4 class="list-group-item-heading">
              <%= link_to role.student.name, role.student.user %>
            </h4>
            <p class="list-group-item-text">
              <% if role.student.is_male? %>
                Monitor de <%= role.request_for_teaching_assistant.course.course_code %>
              <% else %>
                Monitora de <%= role.request_for_teaching_assistant.course.course_code %>
              <% end %>
            </p>
          </div>
          <div class="col-sm-8">
            <% if role.active %>
              <div class="row">
                <% @semester.months.each do |month| %>
                  <div class="col-sm-3 text-center">
                    <div class="row">
                      <%= "#{months_to_names[month]}" %>:
                    </div>
                    <div class="row">
                      <% status = role.frequency_status_for_month(month) %>
                      <% color = "black" %>
                      <% if status == "Pendente" %>
                        <div class="col-sm-12 col-lg-6 text-center">
                          <%= button_to "Presente", { controller: "assistant_frequency", action: "mark_assistant_role_frequency", role: role.id, month: month, presence: true, pid: role.professor.id}, method: :post, class: "btn btn-primary btn-xs", data: { confirm: 'Deseja mesmo marcar presença para este monitor?' } %>
                        </div>
                        <div class="col-sm-12 col-lg-6 text-center">
                          <%= button_to "Ausente", { controller: "assistant_frequency", action: "mark_assistant_role_frequency", role: role.id, month: month, presence: false, pid: role.professor.id}, method: :post, class: "btn btn-primary btn-xs", data: { confirm: 'Deseja mesmo marcar ausência para este monitor?' }  %>
                        </div>
                      <% else %>
                        <% if status == "Presente"
                              color = "green"
                           elsif status == "Ausente"
                              color = "red"
                           elsif status == "---"
                              color = "gray"
                            elsif status == "Pago"
                              color = "blue"
                           else
                              color = "darkgoldenrod"
                           end
                        %>
                        <div class="row">
                          <%= content_tag :span, style: "color:#{color};" do -%>
                            <%= status %>
                          <% end -%>
                          <% if status != "---" %>
                            <%= link_to edit_assistant_frequency_comment_path(role.frequency_for_month(month)), "data-toggle" => "tooltip", title: "Fazer observação" do %>
                              <span class="glyphicon glyphicon-comment"></span>
                            <% end %>
                          <% end %>
                        </div>
                        <div class="row">
                          <% if status != "---" %>
                            <%= role.frequency_for_month(month).comment %>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              <p class="text-center">Desativado</p>
            <% end %>
          </div>
        </div>
        <div style="height:1em;"></div>
        <div class="row text-center">
          <% if @semester.evaluation_period %>
            <% if role.assistant_evaluation %>
              <%= button_link_to "Mudar avaliação", edit_assistant_evaluation_path(role.assistant_evaluation) %>
            <% else %>
              <%= button_link_to "Avaliar", new_assistant_evaluation_path(role) %>
            <% end %>
          <% elsif role.assistant_evaluation %>
            <%= button_link_to "Ver avaliações", assistant_evaluations_for_student_path(role.student) %>
          <% else %>
            <%= button_link_to "Avaliar", "#", class: "btn btn-info disabled"%>
          <% end %>
          <% if role.report_filled? %>
            <%= button_link_to "Imprimir relatório", print_report_path(role.id, :format => :pdf), target: "_blank" %>
          <% else %>
            <%= button_link_to "Imprimir relatório", "#", class: "btn btn-info disabled"%>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

app/views/assistant_roles/report_form.html.erb
<h1>Relatório de monitoria</h1>

<%= render 'report_form' %>